# Generated by Django 4.1.6 on 2023-05-26 07:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import truck_app.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationMap",
            fields=[
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip", models.IntegerField(primary_key=True, serialize=False)),
                ("latitude", models.DecimalField(decimal_places=5, max_digits=22)),
                ("longitude", models.DecimalField(decimal_places=5, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=5,
                        unique=True,
                        validators=[truck_app.models.validate_truck_number],
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_location",
                        to="truck_app.locationmap",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField()),
                (
                    "weight",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1000),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="cargo_photos/%Y/%m/%d/"),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_delivery",
                        to="truck_app.locationmap",
                    ),
                ),
                (
                    "pick_up",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_pick_up",
                        to="truck_app.locationmap",
                    ),
                ),
            ],
        ),
    ]
