# Generated by Django 4.1.6 on 2023-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("truck_app", "0003_auto_20230525_0939"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goods",
            options={"verbose_name_plural": "Goods"},
        ),
        migrations.AlterModelOptions(
            name="locationmap",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="truck",
            options={"verbose_name_plural": "Trucks"},
        ),
    ]
